import Head from "next/head";
import styles from "../styles/Home.module.css";
import Banner from "../components/banner/Banner";
import NavBar from "../components/nav/navbar";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Troubleflix</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <NavBar username="Toto@gmail.com" />
      <Banner
        title="The Godfather"
        subTitle="Sicilian Mafia story in US"
        imgUrl="/static/The_Godfather_movie_logo.png"
      />
      {/*<Card/>*/}
    </div>
  );
}
