import Head from "next/head";
import styles from "../styles/Home.module.css";

import Banner from "../components/banner/Banner";
import NavBar from "../components/nav/navbar";
import SectionCards from "../components/card/section-cards";

import { getVideos, getPopularVideos } from "../lib/videos";

//Server side rendering
export async function getServerSideProps() {
  const disneyVideos = await getVideos("marvel trailer");
  const popularVideos = await getPopularVideos();
  const docuVideos = await getVideos("docu");
  const cookingVideos = await getVideos("chef");
  return {
    props: { disneyVideos, popularVideos, docuVideos, cookingVideos },
  };
}

export default function Home({
  disneyVideos,
  popularVideos,
  docuVideos,
  cookingVideos,
}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Troubleflix</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.main}>
        <NavBar />
        <Banner
          title="Snatch"
          subTitle="A Gipsy always have a plan"
          imgUrl="/static/snatch.jpg"
        />
        <div className={styles.sectionWrapper}>
          <SectionCards title="Marvel" videos={disneyVideos} size="large" />
          <SectionCards title="Popular" videos={popularVideos} size="small" />
          <SectionCards title="Documentary" videos={docuVideos} size="medium" />
          <SectionCards title="Cooking" videos={cookingVideos} size="small" />
        </div>
      </div>
    </div>
  );
}
