import Head from "next/head";
import styles from "../styles/Home.module.css";

import Banner from "../components/banner/Banner";
import NavBar from "../components/nav/navbar";
import SectionCards from "../components/card/section-cards";

import {
  getVideos,
  getPopularVideos,
  getWatchItAgainVideos,
} from "../lib/videos";

//Server side rendering
export async function getServerSideProps() {
  const userId = "did:ethr:0x3B22A8119eB4Ab0D1BaEEcb69995f086F241ea2f";
  const token =
    "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3N1ZXIiOiJkaWQ6ZXRocjoweDNCMjJBODExOWVCNEFiMEQxQmFFRWNiNjk5OTVmMDg2RjI0MWVhMmYiLCJwdWJsaWNBZGRyZXNzIjoiMHgzQjIyQTgxMTllQjRBYjBEMUJhRUVjYjY5OTk1ZjA4NkYyNDFlYTJmIiwiZW1haWwiOiJ0aGliYXVsdGouZGV2QGdtYWlsLmNvbSIsIm9hdXRoUHJvdmlkZXIiOm51bGwsInBob25lTnVtYmVyIjpudWxsLCJhZG1pbiI6dHJ1ZSwiaWF0IjoxNjUxMDQ4OTE0LCJleHAiOjE2NTE2NTM3MTQsImh0dHBzOi8vaGFzdXJhLmlvL2p3dC9jbGFpbXMiOnsieC1oYXN1cmEtYWxsb3dlZC1yb2xlcyI6WyJ1c2VyIiwiYWRtaW4iXSwieC1oYXN1cmEtZGVmYXVsdC1yb2xlIjoidXNlciIsIngtaGFzdXJhLXVzZXItaWQiOiJkaWQ6ZXRocjoweDNCMjJBODExOWVCNEFiMEQxQmFFRWNiNjk5OTVmMDg2RjI0MWVhMmYifX0.IdnKTqn9E1HGeptAP5QJepIVLlY3GsDtKuMI3jHBWIU";

  const watchItAgainVideos = await getWatchItAgainVideos(userId, token);
  console.log({ watchItAgainVideos });
  const disneyVideos = await getVideos("marvel trailer");
  const popularVideos = await getPopularVideos();
  const docuVideos = await getVideos("docu");
  const cookingVideos = await getVideos("chef");
  return {
    props: {
      watchItAgainVideos,
      disneyVideos,
      popularVideos,
      docuVideos,
      cookingVideos,
    },
  };
}

export default function Home({
  watchItAgainVideos,
  disneyVideos,
  popularVideos,
  docuVideos,
  cookingVideos,
}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Troubleflix</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.main}>
        <NavBar />
        <Banner
          title="Snatch"
          subTitle="A Gipsy always have a plan"
          imgUrl="/static/snatch.jpg"
          videoId="m9EX0f6V11Y"
        />
        <div className={styles.sectionWrapper}>
          <SectionCards title="Marvel" videos={disneyVideos} size="large" />
          <SectionCards
            title="Watch it again"
            videos={watchItAgainVideos}
            size="small"
          />
          <SectionCards title="Popular" videos={popularVideos} size="small" />
          <SectionCards title="Documentary" videos={docuVideos} size="medium" />
          <SectionCards title="Cooking" videos={cookingVideos} size="small" />
        </div>
      </div>
    </div>
  );
}
